### ISSUE TITLE
Missing DB Structure

### ISSUE THREAD

**Issue by Venrir** [Tromodolo/Erin#16]
How can people work on it without a MySQL Table Structure :c

**Comment by Tromodolo** [comment]
Since I was working on this closed with friends who shared my online DB, it didn't occur to me to make a table structure other people can use. Sorry, I'll get on making one automatically create in code either tomorrow or during the weekend. I can however probably get you a .sql file to import if that would be fine.

**Comment by Venrir** [comment]
A SQL file would also be fine. Can also just make it automatically be added c:Am 14.06.2017 03:48 schrieb Tromodolo <notifications@github.com>:Since I was working on this closed with friends who shared my online DB, it didn't occur to me to make a table structure other people can use. Sorry, I'll get on making one automatically create in code either tomorrow or during the weekend. I can however probably get you a .sql file to import if that would be fine.

**Comment by Tromodolo** [comment]
https://a.doko.moe/fzkabi.sql

Here's an .sql file if you want to import it. Don't mind the commandlist or usagestats tables. Those are used just to get information from the live bot that's up to the website for statistics. 

This should work, however if it doesn't, I'll be sure to help you get it running when I wake up tomorrow.
